version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    environment:
      GK_LOCK_DEFAULT_BRANCH: saga
    steps:
      - checkout

      - run:
          name: Set up GitHub credentials
          command:
            echo "machine github.com login ${GH_USERNAME} password ${GH_TOKEN}"
            > ~/.netrc

      - run:
          name: Install latest npm
          command: sudo npm install -g npm@

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci --no-audit

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Compile TypeScript
          command: npx tsc

      - run:
          name: Run tests
          command: npm test

      - run:
          when: on_success
          name: Run semantic relase
          command: |
            npm i --no-save semantic-release;
            npx semantic-release || true

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: bifravst
