version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    environment:
      GK_LOCK_DEFAULT_BRANCH: saga
    steps:
      - checkout

      - run:
          name: Install latest npm
          command: sudo npm install -g npm@

      - run:
          name: Install Greenkeeper
          command: sudo npm i -g greenkeeper-lockfile@2
      - run:
          name: Update lockfile
          command: npx greenkeeper-lockfile-update

      - run:
          name: Install dependencies
          command: npm ci --no-audit

      - run:
          name: Compile TypeScript
          command: npx tsc

      - run:
          name: Run tests
          command: npm test

      - run:
          when: on_success
          name: Upload lockfile
          command: npx greenkeeper-lockfile-upload

      - run:
          when: on_success
          name: Run semantic relase
          command: |
            npm i semantic-release;
            npx semantic-release || true

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: bifravst
